const mongoose = require("mongoose");

const customerSchema = new mongoose.Schema(
    {
        // Vendor who owns this customer
        vendorId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true,
        },

        // Customer number generated by MilkBook
        customerNumber: {
            type: Number,
            required: true,
        },

        // Customer basic information
        name: {
            type: String,
            required: true,
            trim: true,
        },

        phone: {
            type: String,
            required: true,
            trim: true,
        },

        alternatePhone: {
            type: String,
            default: "",
            trim: true,
        },

        address: {
            type: String,
            default: "",
            trim: true,
        },

        // Milk/customer billing information
        ratePerLiter: {
            type: Number,
            default: 0,
            min: 0,
        },

        dailyQuantity: {
            type: Number,
            default: 0,
            min: 0,
        },

        // Morning / Evening / Both etc.
        shift: {
            type: String,
            default: "",
            trim: true,
        },

        // Product used by the customer
        product: {
            type: String,
            default: "",
            trim: true,
        },

        // Multiple products if required
        products: {
            type: [String],
            default: [],
        },

        // Billing cycle in days
        billingCycleDays: {
            type: Number,
            default: 30,
            min: 1,
        },

        // Active / Inactive
        status: {
            type: String,
            enum: ["active", "inactive"],
            default: "active",
        },

        startDate: {
            type: Date,
            default: Date.now,
        },

        // Delivery agent assigned to customer
        deliveryAgentId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
    },
    {
        timestamps: true,
    }
);

// A customer number should be unique for each vendor
customerSchema.index(
    {
        vendorId: 1,
        customerNumber: 1,
    },
    {
        unique: true,
    }
);

module.exports = mongoose.model("Customer", customerSchema);